version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/python:3.7-buster
    working_directory: /home/circleci/tszip
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci *
      - restore_cache:
          key: tszip-{{ .Branch }}
      - run:
          name: Install dependencies and set path
          command: |
            sudo apt-get install libgsl-dev # Needed for msprime
            pip install --user -r requirements/development.txt
            pip install twine --user
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - save_cache:
          key: tszip-{{ .Branch }}
          paths:
            - "/home/circleci/.local"

      - run:
          name: Run Python tests 
          command: |
            # Run setup.py so that the version is defined
            python3 setup.py build
            python3 -m pytest --cov=tszip --cov-report=xml --cov-branch -n 2 tests
            rm .coverage

      - codecov/upload:
          token: CODECOV_TOKEN

      - run:
          name: Build Python package
          command: |
            rm -fR build
            python setup.py sdist
            python setup.py check
            python -m twine check dist/*.tar.gz
            python -m venv venv
            source venv/bin/activate 
            pip install --upgrade setuptools pip wheel
            python setup.py build_ext
            python setup.py egg_info
            python setup.py bdist_wheel
            pip install dist/*.tar.gz 

      - run:
          name: Build docs
          command: |
            cd docs && make
