name: Build Docs
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
jobs:
  Docs:
    uses: tskit-dev/.github/.github/workflows/docs-build-template.yml@main
    with:
      requirements-path: requirements/CI-docs.txt